---
name: 01 Basic Docker Build
# simplest workflow possible
#vai 
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    environment: Teste
    runs-on: ubuntu-latest
    steps:           
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: kevinpiovezan/docker-ci-automation:latest,kevinpiovezan/docker-ci-automation:02
          cache-from: type=gha
          cache-to: type=gha,mode=max